### ISSUE TITLE
Please update Lab 05 peering settings

### ISSUE THREAD

**Issue by hiryamada** [MicrosoftLearning/AZ-104JA-MicrosoftAzureAdministrator#17]
# Module: 05
## Lab/Demo: 05

Hi, please update Lab 05, especially peering settings tables. Recently Azure portal peering setting page were changed significantly, so students can't continue lab hands-on with current instructions.

Also please note that Japanese version of Azure portal don't localized yet, so please just copy the peering setting tables of English version and paste them to the Japanese lab instructions.

reference:
https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_05-Implement_Intersite_Connectivity.md

**Comment by junichia** [comment]
I've pull requested.

**Comment by LuongNguyen0906** [comment]
Hi @junichia, 

Since your pull request was meagered to master branch, should I close the issue?

Thanks.

**Comment by hiryamada** [comment]
Yes, thank you very much!
