### ISSUE TITLE
wrong Lab8 link position in Lab content directory page

### ISSUE THREAD

**Issue by hiryamada** [MicrosoftLearning/AZ-104JA-MicrosoftAzureAdministrator#31]
https://microsoftlearning.github.io/AZ-104JA-MicrosoftAzureAdministrator/

Could you please move lab8 to right position (after lab7)?

**Comment by hiryamada** [comment]
I made pull request https://github.com/MicrosoftLearning/AZ-104JA-MicrosoftAzureAdministrator/pull/32

**Comment by LuongNguyen0906** [comment]
i will close issue, since issue has been fixed.
