### ISSUE TITLE
LAB_03b If you enter "空" or "null", the disk cannot be deployed normally.

### ISSUE THREAD

**Issue by lezoid** [MicrosoftLearning/AZ-104JA-MicrosoftAzureAdministrator#33]
# Module: 03
#### Step: 08
https://github.com/MicrosoftLearning/AZ-104JA-MicrosoftAzureAdministrator/blob/master/Instructions/Labs/LAB_03b-Manage_Azure_Resources_by_Using_ARM_Templates.md

1. **「カスタム デプロイ」** ブレードに戻って、次の設定を指定します。
    | 設定 | 値 |
    | オプションを作成する | **空** |

The issue does not occur in the English version of the page.
case by the Japanese translation.

Japanese word "空" is  "null (no character input)".

If you enter empty or null, the disk cannot be deployed normally.
Therefore, it is correct to write **""empty""** here in the Japanese version as well as in the English page.

---
この問題は英語版のページでは発生しません。
の原因は、日本語の翻訳に問題があります。

日本語の「空」は「null（文字入力をしない）」と認識される事が大半だと思います。

"空"やnullを入力した場合、ディスクを正常に展開できません。
そのため、英語版ページと同様に、日本語版でもここに「empty」と書くのが正しいと思います。

**Comment by LuongNguyen0906** [comment]
Fixed as suggested.
i will close issue.
