### ISSUE TITLE
username is wrong (mistranslate)

### ISSUE THREAD

**Issue by yokoyama-tetsuya** [MicrosoftLearning/AZ-104JA-MicrosoftAzureAdministrator#74]
# Module: 04
#### Step: 12 & 14

Description of issue
受講生のユーザー名と Pa55w.rd1234 パスワード
should be
ユーザー名 Student とパスワード Pa55w.rd1234

Repro steps:
just mistranslate

**Comment by VietTran0302** [comment]
fixed
